site_name: Leynier Gutiérrez González
site_url: https://leynier.github.io
repo_url: https://github.com/leynier
edit_uri: ""

theme:
  name: material
  logo: assets/images/avatar.jpg
  favicon: assets/images/avatar.jpg
  features:
    # - navigation.instant
    - navigation.tabs
    - toc.integrate
    - navigation.top
    - header.autohide
  palette:
    scheme: slate
    primary: black
    accent: light blue

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - meta
  - toc:
      permalink: 🔗

google_analytics:
  - G-1ZVVREL82C
  - auto

nav:
  - Home:
    - Intro: index.md
    - Blog 📝: ./blog
  - Blog 📝:
    - Last Posts: blog/index.md
    - Inferfuzzy: blog/inferfuzzy/index.md
    - Hidato - Haskell: blog/hidato-haskell/index.md
    - Cuba Weather - De Cuba Para Cuba: blog/cuba-weather-de-cuba-para-cuba/index.md

copyright: Copyright &copy; Leynier Gutiérrez González

extra:
  disqus: leynier
  manifest: manifest.json
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/leynier
      name: LinkedIn
    - icon: fontawesome/brands/github
      link: https://github.com/leynier
      name: GitHub
    - icon: fontawesome/solid/code
      link: https://profile.codersrank.io/user/leynier
      name: Codersrank
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/leynier41
      name: Twitter
    - icon: fontawesome/brands/telegram
      link: https://t.me/leynier
      name: Telegram
    - icon: fontawesome/solid/paper-plane
      link: mailto:leynier41@gmail.com
      name: Gmail
