site_name: Leynier Gutiérrez González
site_url: https://leynier.github.io
repo_url: https://github.com/leynier
edit_uri: ""

theme:
  name: material
  logo: assets/images/avatar.jpg
  favicon: assets/images/avatar.jpg
  features:
    - navigation.instant
    - navigation.tabs
  palette:
    primary: black
    accent: light blue

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: 🔗

nav:
  - Home: index.md
  - Projects:
    - Covid19 Cuba Data: projects/covid19-cuba-data/index.md
    - Cuba Weather: projects/cuba-weather/index.md
    - FuzzPy: projects/fuzzpy/index.md

copyright: Copyright &copy; Leynier Gutiérrez González

extra:
  manifest: manifest.json
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/leynier
      name: LinkedIn
    - icon: fontawesome/brands/github
      link: https://github.com/leynier
      name: GitHub
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/leynier
      name: GitLab
    - icon: fontawesome/solid/code
      link: https://profile.codersrank.io/user/leynier
      name: Codersrank
    - icon: fontawesome/brands/dev
      link: https://dev.to/leynier
      name: Dev.to
    - icon: fontawesome/brands/stack-overflow
      link: https://stackoverflow.com/users/8921443/leynier-guti%C3%A9rrez-gonz%C3%A1lez
      name: Stack Overflow
    - icon: fontawesome/brands/researchgate
      link: https://www.researchgate.net/profile/Leynier_Gutierrez_Gonzalez
      name: Research Gate
    - icon: fontawesome/brands/medium
      link: https://medium.com/@leynier41
      name: Medium
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/leynier41
      name: Twitter
    - icon: fontawesome/brands/telegram
      link: https://t.me/leynier
      name: Telegram
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/leynier41
      name: Facebook
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/leynier41
      name: Instagram
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCT1z3Pckv-U31HhL31e--rw
      name: Youtube
    - icon: fontawesome/solid/paper-plane
      link: mailto:leynier41@gmail.com
      name: Gmail
