name: deploy
on:
  push:
    branches:
      - master
jobs:
  # deploy:
  #   runs-on: ubuntu-latest
  #   if: github.event.repository.fork == false
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-python@v4
  #       with:
  #         python-version: "3.10"
  #     - run: pip install git+https://${GH_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git
  #       env:
  #         GH_TOKEN: ${{ secrets.GH_TOKEN }}
  #     - run: mkdocs gh-deploy --force -f mkdocs.insiders.yml
  deploy-non-insiders:
    runs-on: ubuntu-latest
    # if: github.event.repository.fork == true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force
